use_frameworks!

platform :ios, '8.0'

target 'rudder-intergration-intercom-ios_Example' do
  pod 'rudder-intergration-intercom-ios', :path => '../'

  target 'rudder-intergration-intercom-ios_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
